language: node_js
node_js:
  - '14'
cache:
  yarn: true
  directories:
    - public
    - .cache
script:
  - yarn build

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  local_dir: dist
  keep-history: true
  target_branch: gh-pages
  on:
    branch: master
